from __future__ import annotations

from pathlib import Path

import streamlit as st

from causal_app.utils import get_run_record, list_run_records


def _download_file(label: str, path: Path, mime: str) -> None:
    if not path.exists():
        st.warning(f"Missing file: {path.name}")
        return
    st.download_button(
        label=label,
        data=path.read_bytes(),
        file_name=path.name,
        mime=mime,
        use_container_width=True,
    )


st.title("Export")
st.caption(
    "Download real output files generated by the extracted engine. "
    "The workbook is business-oriented, but export history is still file-backed rather than Postgres-backed."
)

run_records = [record for record in list_run_records() if record.export_path.exists()]
if not run_records:
    st.info("No exportable runs are available yet. Use the Upload page to execute the pipeline first.")
    st.stop()

default_run_id = st.session_state.get("selected_run_id", run_records[0].run_id)
run_ids = [record.run_id for record in run_records]
if default_run_id not in run_ids:
    default_run_id = run_ids[0]

selected_run_id = st.selectbox(
    "Runs with generated exports",
    options=run_ids,
    index=run_ids.index(default_run_id),
    format_func=lambda run_id: next(
        (
            f"{record.created_at or 'unknown'} | {record.run_id} | export={record.export_path.name}"
            for record in run_records
            if record.run_id == run_id
        ),
        run_id,
    ),
)
st.session_state["selected_run_id"] = selected_run_id
selected_run = get_run_record(selected_run_id)
if selected_run is None:
    st.error("The selected run could not be loaded.")
    st.stop()

st.subheader("Selected Export Bundle")
st.write(
    {
        "run_id": selected_run.run_id,
        "export_workbook": str(selected_run.export_path),
        "recommendations_csv": str(selected_run.recommendations_path),
        "rejected_rows_csv": str(selected_run.rejected_rows_path),
        "policy_options_csv": str(selected_run.policy_options_path),
    }
)

st.subheader("Download Files")
download_columns = st.columns(2)
with download_columns[0]:
    _download_file("Download Excel Workbook", selected_run.export_path, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    _download_file("Download Customer Action List", selected_run.recommendations_path, "text/csv")

with download_columns[1]:
    _download_file("Download Reject Report", selected_run.rejected_rows_path, "text/csv")
    _download_file("Download Policy Options", selected_run.policy_options_path, "text/csv")

st.subheader("Export Coverage")
st.markdown(
    """
Currently generated by the engine:

- Excel workbook with `Summary`, `Customer_Action_List`, `Reject_Report`, `Run_Metadata`, and `Field_Definitions`
- `Customer_Action_List` includes deterministic `priority_band`, `priority_score`, and `reason_short`
- `Reject_Report` includes rule-based rejection details for operations follow-up
- `recommendations.csv` remains the technical pipeline output behind the workbook
- `policy_options.csv` remains a technical support file for inspection, not a sales-facing sheet

Not yet generated separately:

- a polished business-facing dashboard export
- DB-backed export history or audit trail
"""
)
